# Generated by Django 4.1.5 on 2023-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serov_academy_api', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/student/'),
        ),
    ]
