# Generated by Django 4.1.5 on 2023-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serov_academy_api', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='payment_year',
            field=models.CharField(default='2023', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='blood',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='blood',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/trainer/'),
        ),
    ]
