# Generated by Django 4.1.5 on 2023-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serov_academy_api', '0004_studentpayment_payment_year_alter_student_blood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='payment_due',
            field=models.CharField(default='00', max_length=5),
        ),
    ]
